stages:
  data_ingestion:
    cmd: python src/lead_scoring/pipelines/pip_01_data_ingestion.py
    deps: 
      - src/lead_scoring/pipelines/pip_01_data_ingestion.py  # Corrected!  Use the data ingestion script itself
      - config/data-ingestion.yaml
    outs:
      - artifacts/data_ingestion/data-ingestion-metadata.json
      - artifacts/data_ingestion/website_visitors.parquet