
artifacts_root: artifacts

data_validation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/website_visitors.parquet
  val_status: artifacts/data_validation/validation_status.json
  critical_columns:
    - 'lead_origin'
    - 'lead_source'
    - 'do_not_email'
    - 'converted'
    - 'total_visits'
    - 'time_on_website'
    - 'page_views_per_visit'
    - 'last_activity'
    - 'specialization'
    - 'hear_about_x'
    - 'current_job'
    - 'course_selection_factor'
    - 'tags'
    - 'city'
    - 'activity_index'
    - 'profile_index'
    - 'free_interview_copy'
    - 'last_notable_activity'
   