lead_origin:
  type: string
  constraints:
    enum:
      - API
      - Landing Page Submission
      - Lead Add Form
      - Lead Import
      - Quick Add Form

lead_source:
  type: string
  constraints:
    enum:
      - Google
      - Direct Traffic
      - Olark Chat
      - Organic Search
      - Reference
      - Welingak Website
      - Referral Sites
      - Social Media
      - Others

last_activity:
  type: string
  constraints:
    enum:
      - Email Opened
      - SMS Sent
      - Olark Chat Conversation
      - Page Visited on Website
      - Converted to Lead
      - Email Bounced
      - Email Link Clicked
      - others
      - Form Submitted on Website

specialization:
  type: string
  constraints:
    enum:
      - Management
      - Others
      - Business Administration
      - Banking, Investment And Insurance
      - Media and Advertising
      - Travel and Tourism
      - International Business
      - E-Business
      - Rural and Agribusiness
      - Services Excellence

hear_about_x:
  type: string
  constraints:
    enum:
      - Other
      - Online Search
      - Word Of Mouth
      - Student of SomeSchool
      - Multiple Sources
      - SMS
      - Advertisements
      - Social Media
      - Email

current_job:
  type: string
  constraints:
    enum:
      - Unemployed
      - Working Professional
      - Student
      - Other
      - Businessman
      - Housewife

course_selection_factor:
  type: string
  constraints:
    enum:
      - Better Career Prospects
      - Flexibility & Convenience
      - Other

tags:
  type: string
  constraints:
    enum:
      - Others
      - Will revert after reading the email
      - Try Calling again
      - Interested in other courses
      - Already a student
      - Closed by Horizzon
      - Not Interested/Not Eligible
      - Lost
      - No phone number
      - Interested  in full time MBA
      - Graduation in progress
      - Considering next admission
      - in touch with EINS
      - Want to take admission but has financial problems
      - In confusion whether part time or DLP
      - Lateral student
      - Univerity Recongnition issues

city:
  type: string
  constraints:
    enum:
      - Mumbai
      - Other Cities
      - Other Cities of Maharashtra
      - Thane & Outskirts
      - Other Metro Cities
      - Tier II Cities

activity_index:
  type: string
  constraints:
    enum:
      - High
      - Medium
      - Low

profile_index:
  type: string
  constraints:
    enum:
      - High
      - Medium
      - Low

last_notable_activity:
  type: string
  constraints:
    enum:
      - Modified
      - Email Opened
      - SMS Sent
      - Page Visited on Website
      - Olark Chat Conversation
      - Email Link Clicked
      - Email Bounced
      - Unsubscribed
      - Unreachable
      - Had a Phone Conversation
      - Email Marked Spam
      - Approached upfront
      - Resubscribed to emails
      - View in browser link Clicked
      - Form Submitted on Website
      - Email Received

do_not_email:
  type: integer
  constraints:
    minimum: 0
    maximum: 1

total_visits:
  type: float
  constraints:
    minimum: 0
    maximum: 300

time_on_website:
  type: float
  constraints:
    minimum: 0
    maximum: 3000

page_views_per_visit:
  type: float
  constraints:
    minimum: 0
    maximum: 70

free_interview_copy:
  type: integer
  constraints:
    minimum: 0
    maximum: 1

converted:
  type: integer
  constraints:
    minimum: 0
    maximum: 1