# Data ingestion configuration 

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion 
  database_name: website_leads
  collection_name: website_traffic_data
  batch_size: 2000


