# Data ingestion configuration 

artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion 
  database_name: leads
  collection_name: web_leads
  batch_size: 2000
  get_user_name: John Doe


