XGBClassifier_params:
  objective: binary:logistic
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.3
  subsample: 0.8
  colsample_bytree: 1
  gamma: 0.0
  reg_alpha: 0
  reg_lambda: 1
  random_state: 42

  
