

prediction_pipeline:
  model_path: artifacts/model_trainer/leads_score.joblib
  data_preprocessor: artifacts/data_transformation/preprocessor.joblib
  DB_NAME: leads
  INPUT_COLLECTION : leads_to_predict
  OUTPUT_COLLECTION: predicted_leads

