sweep:
  method: random
  metric:
    goal: maximize
    name: validation_f1_score
  parameters:
    n_estimators:
      values: [100, 200, 300]
    max_depth:
      values: [3, 5, 7, 10]
    learning_rate:
      values: [0.01, 0.1, 1]
    reg_alpha:
      values: [0.01, 0.1, 1]
    min_child_weight:
      values: [1, 3, 5]
    gamma:
      values: [0, 0.1, 1]
    reg_lambda:
      values: [1, 2, 5]